initial commit
tomfun/ero-like pull request #15
Opened 2022-12-13 19:50 UTC by ilyapozh

2022-12-20 21:41 UTC, tomfun commented on api/src/filtersQueryPipe.ts
> +export class FiltersQueryPipe extends ValidationPipe {
Why we need `ValidationPipe`? Why we need to validate the query or the nick?

2022-12-20 21:41 UTC, tomfun commented on api/src/report.controller.ts
> -    @Query('nick') nick: string,
Initial idea to create some decorator PaginationFilters or something and use it like that:
```ts
  @Get('/api/report')
  getReports(
    @PaginateQuery query: PaginationQueryDto,
    @PaginationFilters filters: PaginationFilter<Report>, // or `filters: ReportPaginationFilter`
  ): Promise<Paginable<ReportForList>> {
    return this.appService.getList(query,  filters ); // filters.nick and other fields in it
  }
```
But I don't remember when we wanted to do it, here in the current task?

2022-12-20 21:41 UTC, tomfun commented on my-vue3-app/src/components/ReportList.vue
> +          <input v-model="filter.inputValue" placeholder="edit me"/>
Why always input?

2022-12-20 21:41 UTC, tomfun commented on my-vue3-app/src/components/ReportList.vue
> +      handler(newValue, oldValue) {
I will study the subject but not today :(

2023-01-11 18:18 UTC, tomfun commented on api/src/filtersQueryPipe.ts
> +export class FiltersQueryPipe extends ValidationPipe {
https://docs.nestjs.com/pipes#built-in-pipes

2023-01-11 18:28 UTC, tomfun commented on api/src/filtersQueryPipe.ts
> +export class FiltersQueryPipe extends ValidationPipe {
![image](https://user-images.githubusercontent.com/5002775/211888380-48fa5c5e-ed21-45b9-a01f-5cf382c9e485.png)

2023-01-21 15:56 UTC, ilyapozh commented on my-vue3-app/src/components/ReportList.vue
> +          <input v-model="filter.inputValue" placeholder="edit me"/>
If not input then what ?

2023-01-21 21:47 UTC, tomfun commented on api/src/filtersQueryPipe.ts
> +        let filters = {};
much better to set type here
```ts
let filters = {} as TitleQueryDto; // or other type. not sure
```

2023-01-21 21:48 UTC, tomfun commented on api/src/filtersQueryPipe.ts
> +            } : '')
```ts
Object.assign(filters, '')
// ____________________^ very strange
```

2023-01-21 21:53 UTC, tomfun commented on api/src/filtersQueryPipe.ts
> +export class PaginationFilter<ReportEntity> {
'ReportEntity' is defined but never used

2023-01-21 21:55 UTC, tomfun commented on my-vue3-app/src/components/ReportList.vue
> +          <input v-model="filter.inputValue" placeholder="edit me"/>
select!?
but yes, for now it is enough

2023-01-26 20:02 UTC, tomfun requested changes

2023-01-26 20:02 UTC, tomfun commented on my-vue3-app/src/store/reports/state.ts
> +        type: '',
we could use special type `'none'` or `null` for no filtering

2023-01-26 20:02 UTC, tomfun commented on package.json
> +    "start": "docker-compose up & (cd api && npm start) & (cd my-vue3-app && npm run serve)"
Do you really want add this file because of this string?
Better to move this only line to readme

2023-01-28 17:33 UTC, tomfun commented on api/package-lock.json
> +    "node_modules/@angular-devkit/core": {
why at all this file was updated? it seems it is updated by mistake

2023-01-29 21:58 UTC, tomfun commented on my-vue3-app/src/store/reports/state.ts
> +        type: '',
I used `value = undefined` for this case ...

2023-02-11 10:14 UTC, tomfun commented on my-vue3-app/src/components/ReportList.vue
> +      handler(newValue, oldValue) {
seems we fixed it. but the problem with pagination left...

2023-02-11 10:16 UTC, tomfun commented on api/src/filtersQueryPipe.ts
> +        if (value.nick && value.nick.equal) {
seems it is working well

2023-02-11 10:17 UTC, tomfun commented on api/src/filtersQueryPipe.ts
> +    console.log('f2', filters);
rm

2023-02-11 10:21 UTC, tomfun commented on my-vue3-app/src/store/reports/actions.ts
> +      .filter((report) => filterFields.reduce((ok, field) => ok
reduce -> https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/every

2023-02-11 10:23 UTC, tomfun commented on my-vue3-app/src/store/reports/actions.ts
> +  const filterFields = ['nick' as 'nick', 'title' as 'title']
```ts
'nick' as 'nick'
```
->
```ts
'nick' as const
```

2023-02-11 10:23 UTC, tomfun commented on package.json
> +    "start": "docker-compose up & (cd api && npm start) & (cd my-vue3-app && npm run serve)"
We still may create `cheat sheet . md` with instructions

2023-02-11 10:24 UTC, tomfun commented on api/package-lock.json
> +    "node_modules/@angular-devkit/core": {
I fixed it

2023-02-11 10:24 UTC, tomfun requested changes
small fixes

2023-02-11 13:09 UTC, tomfun approved these changes

2023-02-11 17:55 UTC, ilyapozh commented
There is an error on report submit with title or nick fields less then 4 characters, I think we should handle it on the front as well.

2023-02-11 17:57 UTC, ilyapozh commented
![valid](https://user-images.githubusercontent.com/68194331/218273403-22773f9a-9a15-4b47-9da7-4f22c322eddc.png)
Maybe we should validate such nicks and titles somehow

2023-02-11 18:00 UTC, ilyapozh commented
There are empty requests provided when selecting nick/title or equal/start

2023-02-11 18:06 UTC, ilyapozh commented
Shouldn't we add the body of the report not hard-coded?

2023-02-11 19:44 UTC, merged